core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('usuarios.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', index, name='home'),
    # path('create_event', create_event_view, name='create_event'),
    path('mis_eventos', mis_eventos_view, name='mis_eventos'),
    path('evento/<int:id>', evento_edit, name='evento'),
    path('evento/<int:id>/delete', delete_evento, name='eliminar_evento'),
    path('evento/<int:id>/asistir', asistir_a_evento, name='asistir'),
    path('evento/<int:id>/dejar_de_asistir', dejar_de_asistir_a_evento, name='dejar_de_asistir'),
]

usuarios/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Evento(models.Model):
    '''Model definition for Evento.'''
    titulo = models.CharField(max_length=100)
    fecha = models.DateField()
    desde = models.TimeField(null=True, blank=True)
    hasta = models.TimeField(null=True, blank=True)
    todo_el_dia = models.BooleanField(default=False)
    organizador = models.ForeignKey(User, on_delete=models.CASCADE, related_name="organizador")
    lugar = models.CharField(max_length=100)
    cupos = models.IntegerField(default=0, null=True, blank=True)
    cupos_maximos = models.IntegerField(null=True, blank=True)
    cupos_ilimitados = models.BooleanField(default=False)
    precio = models.CharField(max_length=100, null=True, blank=True, default="Gratuito")
    imagen = models.ImageField(upload_to="eventos_aguadas/", null=True, blank=True)
    adicional = models.TextField(null=True, blank=True)
    asistentes = models.ManyToManyField(User, related_name="asistentes", blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        '''Meta definition for Evento.'''

        verbose_name = 'Evento'
        verbose_name_plural = 'Eventos'

    def __str__(self):
        return self.titulo

usuarios/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import Evento

class EventoForm(forms.ModelForm):

    class Meta:
        model = Evento
        exclude = ('organizador', 'cupos', 'asistentes')
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),
            'desde': forms.TimeInput(attrs={'type': 'time'}),
            'hasta': forms.TimeInput(attrs={'type': 'time'}),
        }

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Requerido. Entre una dirección de correo válida.')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import EventoForm
from .models import Evento
from datetime import datetime

# Create your views here.

def index(request):
    eventos = Evento.objects.filter(fecha__gte=datetime.today()).order_by('fecha')
    context = {'messages': [], 
                'eventos': eventos}

    if request.method == 'POST':
        form = EventoForm(request.POST, request.FILES)
        try:

            if form.is_valid():
                form.instance.organizador = request.user
                form.save()
                context['messages'].append('Evento creado exitosamente, puedes ver tus eventos en el apartado "Mis eventos"')

                return redirect('home')
            else:
                context['form'] = form
        
        except Exception as e:
            print(e)
            context['error_message'] = 'No se pudo crear el evento'

    else:
        form = EventoForm()
        context['form'] = form

    
    return render(request, 'home.html', context)

@login_required
def mis_eventos_view(request):
    eventos = Evento.objects.filter(organizador=request.user).order_by('fecha')
    context = {'eventos': eventos}
    return render(request, 'mis_eventos.html', context)

def evento_edit(request, id):
    evento = get_object_or_404(Evento, id=id)

    # Verificar si el usuario es el organizador del evento
    if evento.organizador != request.user:
        return render(request, 'evento.html', {'organizador': False, 'evento': evento})

    if request.method == 'POST':
        form = EventoForm(request.POST, request.FILES, instance=evento)
        if form.is_valid():
            form.save()
            messages.success(request, 'Evento editado exitosamente.')
        else:
            messages.error(request, 'No se pudo editar el evento. Por favor, corrige los errores en el formulario.')
    else:
        form = EventoForm(instance=evento)

    return render(request, 'evento.html', {'form': form, 'organizador': True, 'evento': evento})


@login_required
def delete_evento(request, id):
    evento = Evento.objects.get(id=id)
    if evento.organizador == request.user:
        evento.delete()
        messages.success(request, 'Evento eliminado exitosamente')
        return redirect('mis_eventos')
    else:
        return redirect('evento', id=id)

@login_required
def asistir_a_evento(request, id):
    evento = Evento.objects.get(id=id)
    usuario = request.user
    if evento.cupos_ilimitados == False:
        if int(evento.cupos) >= int(evento.cupos_maximos) :
            messages.error(request, 'No hay cupos disponibles')
            return redirect('evento', id=id)
    evento.asistentes.add(usuario)
    evento.cupos += 1
    evento.save()
    return redirect('evento', id=id)

@login_required
def dejar_de_asistir_a_evento(request, id):
    evento = Evento.objects.get(id=id)
    usuario = request.user
    evento.asistentes.remove(usuario)
    evento.cupos -= 1
    evento.save()
    return redirect('evento', id=id)

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'register.html', {'form': form})
    else:
        form = SignUpForm()

    return render(request, 'register.html' , {'form': form})

def logout_view(request):
    logout(request)
    return redirect('home')

home/templates/CreateEventForm.html
{% if organizador %}
    <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#modal-evento">Editar Evento</button>
{% else %}
<div class="row w-100 d-flex justify-content-center">
    <button class="btn btn-outline-dark mt-4 w-25" data-bs-toggle="modal" data-bs-target="#modal-evento">Publicar nuevo
        evento</button>
{% endif %}

    <div class="modal fade" id="modal-evento" tabindex="-1" aria-labelledby="modal-evento-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modal-evento-label">Publicar nuevo evento</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-floating">
                            <input type="text" class="form-control" id="titulo" name="titulo" placeholder="" required>
                            <label for="titulo">Título del Evento</label>
                        </div>
                        <hr>
                        <div class="col-md-6 mt-3">
                            <div class="form-check form-switch">
                                <label class="form-check-label" for="id_todo_el_dia">Todo el día</label>
                                <input type="checkbox" class="form-check-input" role="switch" id="id_todo_el_dia" name="todo_el_dia">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="time" class="form-control" id="id_desde" name="desde">
                                    <label for="desde">Hora de Inicio</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="time" class="form-control" id="id_hasta" name="hasta">
                                    <label for="hasta">Hora de Finalización</label>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="lugar" name="lugar" required>
                                    <label for="lugar">Lugar del Evento</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="date" class="form-control" id="fecha" name="fecha">
                                    <label for="fecha">Fecha del Evento</label>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" role="switch" id="id_cupos_ilimitados"
                                        name="cupos_ilimitados">
                                    <label class="form-check-label" for="cupos_ilimitados">Cupos Ilimitados</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="number" class="form-control" id="id_cupos_maximos" name="cupos_maximos">
                                    <label for="cupos_maximos">Máximo de Cupos</label>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="precio" name="precio">
                                    <label for="precio">Precio</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="imagen">Imagen del Evento</label>
                                    <input type="file" class="form-control" id="imagen" name="imagen">
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-floating">
                                    <textarea class="form-control" id="adicional" name="adicional" style="height: 100px;"></textarea>
                                    <label for="adicional">Información Adicional</label>
                                </div>
                            </div>
                        </div>
                        <div class="d-grid gap-2 mt-3">

                            <button type="submit" class="btn btn-outline-success" id="btn-publicar-evento">Publicar Evento</button>
                        </div>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
{% if not organizador %}
</div>
{% endif %}

home/templates/EventsList.html
<div class="row">
    {% load static %}
    {% for evento in eventos %}
    <div class="col-md-4 mt-4">
        <div class="card">
            {% if evento.imagen %}
            <img src="{{ evento.imagen.url }}" class="card-img-top" height="400" width="300" style="object-fit: cover;">
            {% else %}
            <img src="{% static 'default.svg' %}" class="card-img-top" height="400" width="300"
                style="object-fit: cover;">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ evento.titulo }}</h5>
                <pre>
Precio: {{ evento.precio }}
Ubicación: {{ evento.lugar }}
Reservas: {{ evento.cupos }} / {% if not evento.cupos_ilimitados %}{{ evento.cupos_maximos }}{% else %}Ilimitados{% endif %}
{% if evento.todo_el_dia  %}Todo el día {% else %}Desde las {{ evento.desde|time:"g:i A" }} Hasta las {{ evento.hasta|time:"g:i A" }}{% endif %}
Organizador: {{ evento.organizador }}
                </pre>

                <div class="d-grid gap-2 mx-5">
                    <a href="{% url 'evento' evento.id %}" class="btn btn-dark">Ver</a>
                </div>
            </div>
            <div class="card-footer text-body-secondary text-center">
                Fecha: {{ evento.fecha }}
            </div>
        </div>
    </div>

    {% empty %}
    <h1>No hay eventos</h1>

    {% endfor %}

    <script>
        document.querySelector('.form-control').addEventListener('input', function (e) {
            let searchValue = e.target.value.toLowerCase();
            let cards = document.querySelectorAll('.card');

            cards.forEach(card => {
                let title = card.querySelector('.card-title').textContent.toLowerCase();
                if (title.includes(searchValue)) {
                    card.parentElement.style.display = '';
                } else {
                    card.parentElement.style.display = 'none';
                }
            });
        });
    </script>
</div>

home/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Eventos Aguadas</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  
  {% block extrahead %}
    
  {% endblock  %}

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
          <a class="navbar-brand" href="/">FiestAguadas</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/' %} active {% endif %}" aria-current="page" href="/">Mural de Eventos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if request.path == '/mis_eventos' %} active {% endif %}" href="{% url 'mis_eventos' %}">Mis Eventos</a>
              </li>
              
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 mx-3">
                {% if user.is_authenticated %}
                
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
              </li>
              {% else %}

              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Registrarse</a>
              </li>
              {% endif %}
            </ul>
            {% if request.path == '/' %}
                
            <form class="d-flex" role="Buscar">
              <input class="form-control me-2" type="Buscar" placeholder="Buscar eventos" aria-label="Buscar">
            </form>
            {% endif %}
          </div>
        </div>
      </nav>

      <div class="container mt-5 mb-5">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
      </div>
</body>
</html>

home/templates/evento.html
{% extends 'base.html' %}


{% block content %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load static %}

<div class="card mb-3">
    {% if evento.imagen %}
    <img src="{{ evento.imagen.url }}" class="card-img-top" alt="imagen de {{ evento.imagen.title }}" style="max-height: 70vh; object-fit: cover">
    {% else %}
    <img src="{% static 'default.svg' %}" class="card-img-top" alt="imagen de {{ evento.imagen.title }}" style="max-height: 70vh; object-fit: cover">
    {% endif %}
    <div class="card-body">
        <h2>{{ evento.titulo }}</h2>
        <hr>
        <h5>Fecha del evento: {{ evento.fecha|default:'El usuario no especificó una fecha para el evento' }} {% if evento.todo_el_dia  %} Todo el día {% elif evento.hora_inicio and evento.hora_fin %} Desde las {{ evento.desde|time:"g:i A" }} Hasta las {{ evento.hasta|time:"g:i A" }} {% else %}{% endif %}</h5>
        <hr>
        <h5>Organizador del Evento: {{ evento.organizador }}</h5>
        <hr>
        <h5>Lugar: {{ evento.lugar }}</h5>
        <hr>
        <h5>Personas que han reservado su cupo: {{ evento.cupos }}</h5>
        <hr>
        <h5>Cupos Máximos: {{ evento.cupos_maximos|default:'Ilimitado' }}</h5>
        <hr>
        <h5>Precio: {{ evento.precio }}</h5>
        <hr>
        <h5>Información Adicional Sobre el Evento:</h5>
        <blockquote class="blockquote">
            <p>{{ evento.adicional|default:"El organizador no poporcionó información adicional" }}</p>
          </blockquote>
        <hr>
        {% if organizador %}
        <h5>Lista de personas que han reservado su cupo para asistir al evento:</h5>
        <table class="table table-sm table-hover mb-5">
            <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nombre de Usuario</th>
                  <th scope="col">Nombre</th>
                  <th scope="col">Apellido</th>
                  <th scope="col">Correo</th>
                </tr>
              </thead>
              <tbody>
                {% for asistente in evento.asistentes.all %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ asistente.username }}</td>
                  <td>{{ asistente.first_name }}</td>
                  <td> {{ asistente.last_name }}</td>
                  <td>{{ asistente.email }}</td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
        <hr>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#modal-evento">Editar
                    Evento</button>
        
                <div class="modal fade" id="modal-evento" tabindex="-1" aria-labelledby="modal-evento-label" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="modal-evento-label">Actualizar Evento</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form action="" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <div class="d-grid gap-2 mt-3">
                                        <button type="submit" class="btn btn-outline-success" id="btn-publicar-evento">Actualizar Evento</button>
                                    </div>
                                </form>
        
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>
        
            </div>
            <div class="col d-flex justify-content-center">
                <a href="{% url 'eliminar_evento' evento.id %}" class="btn btn-outline-danger w-100">Eliminar Evento</a>
            </div>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
        <div class="row d-flex justify-content-center">
            {% if request.user in evento.asistentes.all %}
        
            <a class="btn btn-dark w-25 mt-5" href="{% url 'dejar_de_asistir' evento.id %}">Ya no voy a asistir al evento</a>
        
            {% else %}
        
            <a class="btn btn-outline-dark w-25 mt-5" href="{% url 'asistir' evento.id %}">Reservar mi cupo para asistir al evento</a>
        
            {% endif %}
        
        </div>
        
        {% endif %}
        
        <p class="card-text"><small class="text-body-secondary">Última actualización: {{ evento.updated|naturaltime }}</small></p>
    </div>
</div>

<script src="{% static 'formScript.js' %}"></script>

{% endblock content %}

home/templates/home.html
{% extends 'base.html' %}

{% block extrahead %}
{% load crispy_forms_tags %}
{% load static %}
{% endblock extrahead %}

{% block content %}
{% if user.is_authenticated %}
<h2>Bienvenidx a FiestAguadas @{{ user.username }}!</h2>
<h5 class="mt-4 sa-3">Mira los eventos que tenemos para ti</h5>
{% include 'CreateEventForm.html' %}
{% else %}
<h2>Bienvenidx a FiestAguadas!</h2>
<h5>Inicia Sesión o Registrate para disfrutar al máximo de todo lo que tenemos para ti</h5>
{% endif %}
{% include 'EventsList.html' %}

<script src="{% static 'formScript.js' %}" type="text/javascript"></script>

{% endblock content %}

home/templates/mis_eventos.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
{% include 'EventsList.html' %}
<script src="{% static 'formScript.js' %}"></script>
    
{% endblock content %}

usuarios/templates/login.html
<!DOCTYPE html>
<html lang="es">
<head>
  {% load static %}
  {% load crispy_forms_tags %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FiestAguadas</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <style>
        body{
            background: linear-gradient(135deg, #ff6b6b, #833ab4);;
        }
    </style>

</head>
<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                  <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="{% static 'fondo_login.jpg' %}"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
      
                      <form method="post" action="">
                        {% csrf_token %}
      
                        <div class="d-flex align-items-center mb-3 pb-1">
                          <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                          <span class="h1 fw-bold mb-0">FiestAguadas</span>
                        </div>
      
                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Inicia sesión en tu cuenta</h5>

                        {{ form|crispy }}
      
                        <div class="pt-1 mb-4">
                          <button class="btn btn-dark btn-lg btn-block" type="submit">Iniciar Sesión</button>
                        </div>
      
                        <p style="color: #393f81;">No tienes una cuenta? <a href="{% url 'signup' %}"
                            style="color: #393f81;">Regístrate</a></p>
                      </form>
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</body>
</html>

usuarios/templates/register.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    {% load crispy_forms_tags %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FiestAguadas</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  
  <style>
        body{
            background: linear-gradient(135deg, #ff6b6b, #833ab4);;
        }
    </style>

</head>
<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl">
              <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                  <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="{% static 'fondo_login.jpg' %}"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
                        {% for error in form.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                      <form method="post" action="">
                        {% csrf_token %}
      
                        <div class="d-flex align-items-center mb-3 pb-1">
                          <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                          <span class="h1 fw-bold mb-0">FiestAguadas</span>
                        </div>
      
                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Crea tu cuenta para asistir a la los eventos</h5>
      
                        {{ form|crispy }}
      
                        <div class="d-grid gap-2 mb-4">
                          <button class="btn btn-dark btn-lg btn-block" type="submit">Registrarse</button>
                        </div>
      
                        <p class="mb-5 pb-lg-2" style="color: #393f81;">Ya tienes una cuenta? <a href="{% url 'login' %}"
                            style="color: #393f81;">Inicia sesión</a></p>
                      </form>
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</body>
</html>